/**
 * build-wordlist.ts — reproducible Upwords lexicon pipeline.
 *
 * Source: the SCOWL custom word-list generator at https://app.aspell.net/create,
 * built from the English Speller Database (ESDB / SCOWL) by Kevin Atkinson.
 * SCOWL is distributed under a permissive MIT-style license (free for any use,
 * including commercial, with attribution). The exact source URL + license note
 * are written into the generated seed file's header.
 *
 * Pipeline: download → lowercase → filter to /^[a-z]{2,}$/ (which drops proper
 * nouns, abbreviations, hyphenated words, apostrophes, and accented/foreign
 * forms — exactly the "illegal words" classes) → dedup → sort → emit batched
 * `INSERT OR IGNORE` seed SQL.
 *
 * Run: npm run build:wordlist   (Node 24 runs TypeScript directly)
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// ── Tunable knobs (the frequency cutoff lives here) ──────────────────────────
const CONFIG = {
  size: 50, // SCOWL frequency bucket (10..95). 50 ≈ 63k words; the next bucket (60) ≈ 82k.
  spellings: ["US", "GBs"], // include US + British spellings
  maxVariant: 0, // 0 = primary spelling only (no rare variants)
  diacritic: "strip", // strip accents (café → cafe)
  minLength: 2, // Upwords words are always >= 2 letters
  rowsPerInsert: 500, // multi-row INSERT batch size
};

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT_SQL = resolve(ROOT, "scripts/generated/seed-words.sql");

function generatorUrl(): string {
  const p = new URLSearchParams();
  p.set("max_size", String(CONFIG.size));
  for (const s of CONFIG.spellings) p.append("spelling", s);
  p.set("max_variant", String(CONFIG.maxVariant));
  p.set("diacritic", CONFIG.diacritic);
  p.set("download", "wordlist");
  p.set("encoding", "utf-8");
  p.set("format", "inline");
  return `http://app.aspell.net/create?${p.toString()}`;
}

const url = generatorUrl();
console.log(`↓ downloading SCOWL size ${CONFIG.size} (${CONFIG.spellings.join("+")}) …`);
const res = await fetch(url);
if (!res.ok) throw new Error(`generator returned HTTP ${res.status}`);
const raw = await res.text();

// Keep ONLY tokens that are already all-lowercase ASCII. This rejects proper
// nouns, acronyms, and initialisms (ABC, ACLU, AIDS, AK, …) which SCOWL stores
// capitalized — exactly the "illegal words" we must exclude. We intentionally do
// NOT lowercase first, or those would pollute the lexicon (ABC → abc). Genuine
// words are present separately in lowercase form, so nothing legitimate is lost.
const valid = /^[a-z]{2,}$/;
const words = new Set<string>();
for (const line of raw.split("\n")) {
  const w = line.trim();
  if (w.length >= CONFIG.minLength && valid.test(w)) words.add(w);
}
const sorted = [...words].sort();
console.log(`✓ ${sorted.length} unique words after filter`);
if (sorted.length < 40_000) {
  throw new Error(`only ${sorted.length} words — generator response looks wrong; aborting`);
}

const header = [
  "-- Generated by scripts/build-wordlist.ts — DO NOT EDIT BY HAND.",
  `-- Source: ${url}`,
  "-- SCOWL / English Speller Database (Kevin Atkinson), MIT-style license.",
  `-- ${sorted.length} words · SCOWL size ${CONFIG.size} · spellings ${CONFIG.spellings.join("+")}.`,
  "",
];
const lines = [...header];
for (let i = 0; i < sorted.length; i += CONFIG.rowsPerInsert) {
  // words match /^[a-z]+$/ so there are no quotes/escaping concerns.
  const values = sorted.slice(i, i + CONFIG.rowsPerInsert).map((w) => `('${w}')`).join(",");
  lines.push(`INSERT OR IGNORE INTO words(word) VALUES ${values};`);
}

await mkdir(dirname(OUT_SQL), { recursive: true });
await writeFile(OUT_SQL, lines.join("\n") + "\n", "utf8");
console.log(`✓ wrote ${OUT_SQL}`);
